twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['forms/tailwind_2_layout.html.twig']

when@test:
    twig:
        strict_variables: true
        form_themes: ['forms/tailwind_2_layout.html.twig']