controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

landing_page:
    path: /
    controller: App\Controller\QuackController::landing

app_logout:
    path: /logout
    methods: GET